import 'package:flutter/material.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedGroup6Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedHomeWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedGroup5Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedAcupuntureWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedSearchWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedYogaWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedWhatweofferWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedBeatTheVirusWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle3Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedPhoneWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedVectorWidget10.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle1Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedMeditationWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedGroup2Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle7Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle6Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedFitnessWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle4Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedAlignjustifyWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedGroup3Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedEllipse7Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedGroup4Widget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedHelpcircleWidget.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedVectorWidget9.dart';
import 'package:beat_the_virus/screens/btvhomeapp/generatediphone11promax5widget/generated/GeneratedRectangle8Widget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 575.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 414.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedAlignjustifyWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 30.0,
                child: GeneratedBeatTheVirusWidget(),
              ),
              Positioned(
                left: 364.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedHelpcircleWidget(),
              ),
              Positioned(
                left: 307.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 61.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 131.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 131.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 131.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 131.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 21.0,
                child: GeneratedYogaWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 802.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 21.0,
                child: GeneratedFitnessWidget(),
              ),
              Positioned(
                left: 267.0,
                top: 802.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 21.0,
                child: GeneratedAcupuntureWidget(),
              ),
              Positioned(
                left: 269.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 21.0,
                child: GeneratedMeditationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 472.0,
                height: 137.0,
                child: GeneratedVectorWidget9(),
              ),
              Positioned(
                left: 414.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 469.0,
                height: 137.0,
                child: GeneratedVectorWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 413.5,
                height: 200.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 30.0,
                child: GeneratedWhatweofferWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 832.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 72.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 842.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 42.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 181.0,
                top: 842.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 44.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 352.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 45.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 44.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 842.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPhoneWidget(),
              )
            ]),
      ),
    ));
  }
}
